language: objective-c
before_install:
  - sudo gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script:
  - xcodebuild -project OMChainKit/OMChainKit.xcodeproj -scheme OMChainKitTests -sdk iphonesimulator